Repository nephio-project/nephio, pull requests merged in 2023-05, with the labels that each got.

#123 Ipalloc newKO
  go.mod
  go.sum
  krm-functions/lib/ipalloc/v1alpha1/ipalloc.go
  krm-functions/lib/ipalloc/v1alpha1/ipalloc_test.go
Labels: lgtm, approved

#141 Add static type checking for KubeObjectExt methods
  krm-functions/lib/kubeobject/kubeobject.go
  krm-functions/lib/kubeobject/kubeobject_test.go
Labels: lgtm, approved

#163 Add type-safety to KubeObjectExt in a non-backward compatible manner
  krm-functions/lib/interface/v1alpha1/interface.go
  krm-functions/lib/interface/v1alpha1/interface_test.go
  krm-functions/lib/ipalloc/v1alpha1/ipalloc.go
  krm-functions/lib/ipalloc/v1alpha1/ipalloc_test.go
  krm-functions/lib/kubeobject/kubeobject.go
  krm-functions/lib/kubeobject/kubeobject_test.go
  krm-functions/lib/vlanalloc/v1alpha1/vlanalloc.go
  krm-functions/lib/vlanalloc/v1alpha1/vlanalloc_test.go
Labels: lgtm, approved

#170 Improvements for krm-functions/lib/test
  krm-functions/interface-fn/go.sum
  krm-functions/lib/test/krm_fn.go
Labels: lgtm, approved

#173 resourcelist get
  krm-functions/lib/kptrl/kptrl.go
  krm-functions/lib/kptrl/kptrl_test.go
Labels: lgtm, approved

#171 ipam-fn
  krm-functions/ipam-fn/.gitignore
  krm-functions/ipam-fn/Dockerfile
  krm-functions/ipam-fn/Makefile
  krm-functions/ipam-fn/README.md
  krm-functions/ipam-fn/fn/function.go
  krm-functions/ipam-fn/fn/golden_test.go
  krm-functions/ipam-fn/fn/testdata/failure_cases/missing_ipallocation/Kptfile
  krm-functions/ipam-fn/fn/testdata/failure_cases/missing_ipallocation/_expected_error.txt
  krm-functions/ipam-fn/fn/testdata/golden/allocate_loopback/Kptfile
  krm-functions/ipam-fn/fn/testdata/golden/allocate_loopback/_expected.yaml
  krm-functions/ipam-fn/fn/testdata/golden/allocate_loopback/ipallocation.yaml
  krm-functions/ipam-fn/fn/testdata/golden/allocate_network_prefix/Kptfile
  krm-functions/ipam-fn/fn/testdata/golden/allocate_network_prefix/_expected.yaml
  krm-functions/ipam-fn/fn/testdata/golden/allocate_network_prefix/_expected_result.yaml
  krm-functions/ipam-fn/fn/testdata/golden/allocate_network_prefix/ipallocation.yaml
  krm-functions/ipam-fn/fn/testdata/golden/allocate_pool/Kptfile
  krm-functions/ipam-fn/fn/testdata/golden/allocate_pool/_expected.yaml
  krm-functions/ipam-fn/fn/testdata/golden/allocate_pool/ipallocation.yaml
  krm-functions/ipam-fn/go.mod
  krm-functions/ipam-fn/go.sum
Labels: lgtm, approved

#172 vlan-fn
  krm-functions/vlan-fn/.gitignore
  krm-functions/vlan-fn/Dockerfile
  krm-functions/vlan-fn/Makefile
  krm-functions/vlan-fn/README.md
  krm-functions/vlan-fn/fn/function.go
  krm-functions/vlan-fn/fn/golden_test.go
  krm-functions/vlan-fn/fn/testdata/failure_cases/missing_allocation/Kptfile
  krm-functions/vlan-fn/fn/testdata/failure_cases/missing_allocation/_expected_error.txt
  krm-functions/vlan-fn/fn/testdata/failure_cases/missing_allocation/_expected_result.yaml
  krm-functions/vlan-fn/fn/testdata/golden/allocate_vlan/Kptfile
  krm-functions/vlan-fn/fn/testdata/golden/allocate_vlan/_expected.yaml
  krm-functions/vlan-fn/fn/testdata/golden/allocate_vlan/vlanallocation.yaml
  krm-functions/vlan-fn/go.mod
  krm-functions/vlan-fn/go.sum
Labels: lgtm, approved

#175 Ipam vlan readme
  krm-functions/ipam-fn/README.md
  krm-functions/vlan-fn/README.md
Labels: lgtm, approved

#174 krm-specializers
  krm-specializers/pkg/go.mod
  krm-specializers/pkg/go.sum
  krm-specializers/pkg/reconciler/condition.go
  krm-specializers/pkg/reconciler/condition_test.go
  krm-specializers/pkg/reconciler/reconciler.go
  krm-specializers/pkg/resource/error.go
  krm-specializers/pkg/resource/error_test.go
Labels: area/package-specialization, lgtm, approved

#177 specializer operator
  .gitignore
  krm-specializers/operator/Dockerfile
  krm-specializers/operator/Makefile
  krm-specializers/operator/blueprint/fn-config/controller-pod-fn-config.yaml
  krm-specializers/operator/blueprint/specialzer-operator/Kptfile
  krm-specializers/operator/blueprint/specialzer-operator/README.md
  krm-specializers/operator/blueprint/specialzer-operator/app/Kptfile
  krm-specializers/operator/blueprint/specialzer-operator/app/README.md
  krm-specializers/operator/blueprint/specialzer-operator/app/controller/clusterrole-controller.yaml
  krm-specializers/operator/blueprint/specialzer-operator/app/controller/clusterrole-porch.yaml
  krm-specializers/operator/blueprint/specialzer-operator/app/controller/clusterrolebinding-controller.yaml
  krm-specializers/operator/blueprint/specialzer-operator/app/controller/clusterrolebinding-porch.yaml
  krm-specializers/operator/blueprint/specialzer-operator/app/controller/deployment-controller.yaml
  krm-specializers/operator/blueprint/specialzer-operator/app/controller/role-leader-election.yaml
  krm-specializers/operator/blueprint/specialzer-operator/app/controller/rolebinding-leader-election.yaml
  krm-specializers/operator/blueprint/specialzer-operator/app/controller/serviceaccount-controller.yaml
  krm-specializers/operator/blueprint/specialzer-operator/crd/Kptfile
  krm-specializers/operator/blueprint/specialzer-operator/crd/README.md
  krm-specializers/operator/controllers/config/config.go
  krm-specializers/operator/controllers/controllers.go
  krm-specializers/operator/controllers/controllers_test.go
  krm-specializers/operator/controllers/ipam/ipam.go
  krm-specializers/operator/controllers/ipam/ipam_test.go
  krm-specializers/operator/controllers/vlan/vlan.go
  krm-specializers/operator/controllers/vlan/vlan_test.go
  krm-specializers/operator/go.mod
  krm-specializers/operator/go.sum
  krm-specializers/operator/hack/boilerplate.go.txt
  krm-specializers/operator/main.go
Labels: lgtm, approved

#179 reworked repo to allow for mix of specializer controller and regular …
  controllers/pkg/go.mod
  controllers/pkg/go.sum
  controllers/pkg/resource/error.go
  controllers/pkg/resource/error_test.go
  controllers/pkg/specializer-reconciler/condition.go
  controllers/pkg/specializer-reconciler/condition_test.go
  controllers/pkg/specializer-reconciler/reconciler.go
  controllers/specializer-operator/Dockerfile
  controllers/specializer-operator/Makefile
  controllers/specializer-operator/blueprint/fn-config/controller-pod-fn-config.yaml
  controllers/specializer-operator/blueprint/specialzer-operator/Kptfile
  controllers/specializer-operator/blueprint/specialzer-operator/README.md
  controllers/specializer-operator/blueprint/specialzer-operator/app/Kptfile
  controllers/specializer-operator/blueprint/specialzer-operator/app/README.md
  controllers/specializer-operator/blueprint/specialzer-operator/app/controller/clusterrole-controller.yaml
  controllers/specializer-operator/blueprint/specialzer-operator/app/controller/clusterrole-porch.yaml
  controllers/specializer-operator/blueprint/specialzer-operator/app/controller/clusterrolebinding-controller.yaml
  controllers/specializer-operator/blueprint/specialzer-operator/app/controller/clusterrolebinding-porch.yaml
  controllers/specializer-operator/blueprint/specialzer-operator/app/controller/deployment-controller.yaml
  controllers/specializer-operator/blueprint/specialzer-operator/app/controller/role-leader-election.yaml
  controllers/specializer-operator/blueprint/specialzer-operator/app/controller/rolebinding-leader-election.yaml
  controllers/specializer-operator/blueprint/specialzer-operator/app/controller/serviceaccount-controller.yaml
  controllers/specializer-operator/blueprint/specialzer-operator/crd/Kptfile
  controllers/specializer-operator/blueprint/specialzer-operator/crd/README.md
  controllers/specializer-operator/controllers/config/config.go
  controllers/specializer-operator/controllers/controllers.go
  controllers/specializer-operator/controllers/controllers_test.go
  controllers/specializer-operator/controllers/ipam/ipam.go
  controllers/specializer-operator/controllers/ipam/ipam_test.go
  controllers/specializer-operator/controllers/vlan/vlan.go
  controllers/specializer-operator/controllers/vlan/vlan_test.go
  controllers/specializer-operator/go.mod
  controllers/specializer-operator/go.sum
  controllers/specializer-operator/hack/boilerplate.go.txt
  controllers/specializer-operator/main.go
Labels: lgtm, approved

#180 Nad lib Squashed
  krm-functions/lib/go.sum
  krm-functions/lib/nad/v1/nad.go
  krm-functions/lib/nad/v1/nad_test.go
Labels: lgtm, approved

#189 Fix on the docker registry name
  controllers/specializer-operator/Makefile
  controllers/specializer-operator/blueprint/fn-config/controller-pod-fn-config.yaml
  controllers/specializer-operator/blueprint/specialzer-operator/app/controller/deployment-controller.yaml
  krm-functions/nad-fn/makefile
  krm-functions/nfdeploy-fn/makefile
  krm-functions/vlan-fn/Makefile
Labels: area/package-specialization, lgtm, approved

#190 Add new "dnn-fn" and "pipeline-tests" dependencies to krm-functions/lib
  .gitignore
  krm-functions/lib/kubeobject/kubeobject_test.go
  krm-functions/lib/kubeobject/lists.go
  krm-functions/lib/kubeobject/lists_test.go
  krm-functions/lib/kubeobject/testdata/.gitignore
  krm-functions/lib/kubeobject/testdata/formatting/deployment_full.yaml
  krm-functions/lib/kubeobject/testdata/formatting/deployment_full__change_all_fields_expected.yaml
  krm-functions/lib/kubeobject/testdata/formatting/deployment_full__change_list_expected.yaml
  krm-functions/lib/kubeobject/testdata/formatting/deployment_full__change_spec_fields_expected.yaml
  krm-functions/lib/kubeobject/testdata/formatting/deployment_full__change_status_fields_expected.yaml
  krm-functions/lib/kubeobject/testdata/formatting/deployment_full__noop_expected.yaml
  krm-functions/lib/kubeobject/testdata/formatting/deployment_no_status.yaml
  krm-functions/lib/kubeobject/testdata/formatting/deployment_no_status__change_spec_fields_expected.yaml
  krm-functions/lib/kubeobject/testdata/formatting/deployment_no_status__change_status_fields_expected.yaml
  krm-functions/lib/kubeobject/testdata/formatting/setspec__deployment_full__change_spec_fields_expected.yaml
  krm-functions/lib/kubeobject/testdata/formatting/setspec__deployment_no_status__change_spec_fields_expected.yaml
  krm-functions/lib/kubeobject/testdata/formatting/setstatus__deployment_full__change_status_fields_expected.yaml
  krm-functions/lib/kubeobject/testdata/formatting/setstatus__deployment_no_status__change_status_fields_expected.yaml
  krm-functions/lib/kubeobject/testdata/lists/resources.yaml
  krm-functions/lib/test/helpers.go
  krm-functions/lib/test/krm_fn.go
Labels: lgtm, approved

#187 Updated README files for nfdeploy functions
  krm-functions/nfdeploy-fn/amfdeployfn/README.md
  krm-functions/nfdeploy-fn/smfdeployfn/README.md
  krm-functions/nfdeploy-fn/upfdeployfn/README.md
Labels: area/package-specialization, lgtm, approved

#191 nfdeploy-fn: Upgrade dependencies, and align code to the latest APIs
  krm-functions/nfdeploy-fn/amfdeployfn/main.go
  krm-functions/nfdeploy-fn/common/mutator.go
  krm-functions/nfdeploy-fn/go.mod
  krm-functions/nfdeploy-fn/go.sum
  krm-functions/nfdeploy-fn/smfdeployfn/main.go
  krm-functions/nfdeploy-fn/upfdeployfn/main.go
Labels: lgtm, approved

#70 dnn-fn
  krm-functions/dnn-fn/.gitignore
  krm-functions/dnn-fn/Dockerfile
  krm-functions/dnn-fn/Makefile
  krm-functions/dnn-fn/README.md
  krm-functions/dnn-fn/fn/function.go
  krm-functions/dnn-fn/fn/golden_test.go
  krm-functions/dnn-fn/fn/lib.go
  krm-functions/dnn-fn/fn/testdata/clustercontext_without_sitecode/Kptfile
  krm-functions/dnn-fn/fn/testdata/clustercontext_without_sitecode/_expected_results.yaml
  krm-functions/dnn-fn/fn/testdata/clustercontext_without_sitecode/capacity.yaml
  krm-functions/dnn-fn/fn/testdata/clustercontext_without_sitecode/cluster_context.yaml
  krm-functions/dnn-fn/fn/testdata/clustercontext_without_sitecode/dnn.yaml
  krm-functions/dnn-fn/fn/testdata/clustercontext_without_sitecode/ipallocations.yaml
  krm-functions/dnn-fn/fn/testdata/create_owned_resources/Kptfile
  krm-functions/dnn-fn/fn/testdata/create_owned_resources/_expected.yaml
  krm-functions/dnn-fn/fn/testdata/create_owned_resources/capacity.yaml
  krm-functions/dnn-fn/fn/testdata/create_owned_resources/cluster_context.yaml
  krm-functions/dnn-fn/fn/testdata/create_owned_resources/dnn.yaml
  krm-functions/dnn-fn/fn/testdata/deleted_pool/Kptfile
  krm-functions/dnn-fn/fn/testdata/deleted_pool/_expected.yaml
  krm-functions/dnn-fn/fn/testdata/deleted_pool/capacity.yaml
  krm-functions/dnn-fn/fn/testdata/deleted_pool/cluster_context.yaml
  krm-functions/dnn-fn/fn/testdata/deleted_pool/dnn.yaml
  krm-functions/dnn-fn/fn/testdata/deleted_pool/ipallocations.yaml
  krm-functions/dnn-fn/fn/testdata/garbage_collection/Kptfile
  krm-functions/dnn-fn/fn/testdata/garbage_collection/_expected.yaml
  krm-functions/dnn-fn/fn/testdata/garbage_collection/capacity.yaml
  krm-functions/dnn-fn/fn/testdata/garbage_collection/cluster_context.yaml
  krm-functions/dnn-fn/fn/testdata/garbage_collection/ipallocations.yaml
  krm-functions/dnn-fn/fn/testdata/missing_clustercontext/Kptfile
  krm-functions/dnn-fn/fn/testdata/missing_clustercontext/_expected_error.txt
  krm-functions/dnn-fn/fn/testdata/missing_clustercontext/_expected_results.yaml
  krm-functions/dnn-fn/fn/testdata/missing_clustercontext/capacity.yaml
  krm-functions/dnn-fn/fn/testdata/missing_clustercontext/dnn.yaml
  krm-functions/dnn-fn/fn/testdata/missing_clustercontext/ipallocations.yaml
  krm-functions/dnn-fn/fn/testdata/missing_kptfile/_expected_error.txt
  krm-functions/dnn-fn/fn/testdata/missing_kptfile/capacity.yaml
  krm-functions/dnn-fn/fn/testdata/missing_kptfile/cluster_context.yaml
  krm-functions/dnn-fn/fn/testdata/missing_kptfile/dnn.yaml
  krm-functions/dnn-fn/fn/testdata/multiple_clustercontexts/Kptfile
  krm-functions/dnn-fn/fn/testdata/multiple_clustercontexts/_expected_results.yaml
  krm-functions/dnn-fn/fn/testdata/multiple_clustercontexts/capacity.yaml
  krm-functions/dnn-fn/fn/testdata/multiple_clustercontexts/cluster_context.yaml
  krm-functions/dnn-fn/fn/testdata/multiple_clustercontexts/cluster_context_2.yaml
  krm-functions/dnn-fn/fn/testdata/multiple_clustercontexts/dnn.yaml
  krm-functions/dnn-fn/fn/testdata/set_dnn_status/Kptfile
  krm-functions/dnn-fn/fn/testdata/set_dnn_status/_expected.yaml
  krm-functions/dnn-fn/fn/testdata/set_dnn_status/capacity.yaml
  krm-functions/dnn-fn/fn/testdata/set_dnn_status/cluster_context.yaml
  krm-functions/dnn-fn/fn/testdata/set_dnn_status/dnn.yaml
  krm-functions/dnn-fn/fn/testdata/set_dnn_status/ipallocations.yaml
  krm-functions/dnn-fn/go.mod
  krm-functions/dnn-fn/go.sum
  krm-functions/dnn-fn/main.go
Labels: area/package-specialization, lgtm, approved

#193 KRM function pipeline test lib: put input kpt package and expected data into separate subdirectories
  krm-functions/lib/test/krm_fn.go
Labels: lgtm, approved

#200 update specializer
  controllers/specializer-operator/go.mod
  controllers/specializer-operator/go.sum
Labels: lgtm, approved

#199 bootstrap controller
  controllers/pkg/cluster/capi/capi.go
  controllers/pkg/cluster/capi/capi_test.go
  controllers/pkg/cluster/cluster.go
  controllers/pkg/cluster/cluster_test.go
  controllers/pkg/go.mod
  controllers/pkg/go.sum
  controllers/pkg/reconcilers/bootstrap/README.md
  controllers/pkg/reconcilers/bootstrap/reconciler.go
  controllers/pkg/reconcilers/bootstrap/reconciler_test.go
  controllers/pkg/reconcilers/config/config.go
  controllers/pkg/resource/annotations.go
  controllers/pkg/resource/annotations_test.go
  controllers/pkg/resource/api.go
  controllers/pkg/resource/api_test.go
  controllers/pkg/resource/applicator.go
  controllers/pkg/resource/error.go
  controllers/pkg/resource/fake.go
  controllers/pkg/resource/finalizer.go
  controllers/pkg/resource/finalizer_test.go
  controllers/pkg/resource/meta.go
  controllers/pkg/resource/meta_test.go
  controllers/pkg/resource/resource.go
  controllers/pkg/resource/unstructured.go
  controllers/pkg/resource/unstructured_test.go
  controllers/pkg/resource/util.go
  controllers/pkg/resource/util_test.go
Labels: lgtm, approved

#207 Recoinciler interface for controllers to integrate with controller-manager
  controllers/pkg/go.mod
  controllers/pkg/go.sum
  controllers/pkg/reconcilers/reconciler-interface/reconciler_interface.go
Labels: lgtm, approved

#198 repo-token controllers
  controllers/pkg/giteaclient/giteaclient.go
  controllers/pkg/go.mod
  controllers/pkg/go.sum
  controllers/pkg/reconcilers/bootstrap/reconciler.go
  controllers/pkg/reconcilers/bootstrap/reconciler_test.go
  controllers/pkg/reconcilers/config/config.go
  controllers/pkg/reconcilers/reconciler-interface/reconciler_interface.go
  controllers/pkg/reconcilers/repository/README.md
  controllers/pkg/reconcilers/repository/reconciler.go
  controllers/pkg/reconcilers/token/README.md
  controllers/pkg/reconcilers/token/reconciler.go
Labels: lgtm, approved

#195 Additional tests to cover not-ready cases
  krm-functions/nad-fn/testdata/golden/ipallocation_notReady/Kptfile
  krm-functions/nad-fn/testdata/golden/ipallocation_notReady/_expected.yaml
  krm-functions/nad-fn/testdata/golden/ipallocation_notReady/cluster_context.yaml
  krm-functions/nad-fn/testdata/golden/ipallocation_notReady/interface-n3.yaml
  krm-functions/nad-fn/testdata/golden/ipallocation_notReady/interface-n4.yaml
  krm-functions/nad-fn/testdata/golden/ipallocation_notReady/interface-n6.yaml
  krm-functions/nad-fn/testdata/golden/ipallocation_notReady/ipallocation_n3.yaml
  krm-functions/nad-fn/testdata/golden/ipallocation_notReady/ipallocation_n4.yaml
  krm-functions/nad-fn/testdata/golden/ipallocation_notReady/ipallocation_n6.yaml
  krm-functions/nad-fn/testdata/golden/ipallocation_notReady/vlanallocation-n3.yaml
  krm-functions/nad-fn/testdata/golden/ipallocation_notReady/vlanallocation-n4.yaml
  krm-functions/nad-fn/testdata/golden/ipallocation_notReady/vlanallocation-n6.yaml
  krm-functions/nad-fn/testdata/golden/vlanallocation_notReady/Kptfile
  krm-functions/nad-fn/testdata/golden/vlanallocation_notReady/_expected.yaml
  krm-functions/nad-fn/testdata/golden/vlanallocation_notReady/cluster_context.yaml
  krm-functions/nad-fn/testdata/golden/vlanallocation_notReady/interface-n3.yaml
  krm-functions/nad-fn/testdata/golden/vlanallocation_notReady/interface-n4.yaml
  krm-functions/nad-fn/testdata/golden/vlanallocation_notReady/interface-n6.yaml
  krm-functions/nad-fn/testdata/golden/vlanallocation_notReady/ipallocation_n3.yaml
  krm-functions/nad-fn/testdata/golden/vlanallocation_notReady/ipallocation_n4.yaml
  krm-functions/nad-fn/testdata/golden/vlanallocation_notReady/ipallocation_n6.yaml
  krm-functions/nad-fn/testdata/golden/vlanallocation_notReady/vlanallocation-n3.yaml
  krm-functions/nad-fn/testdata/golden/vlanallocation_notReady/vlanallocation-n4.yaml
  krm-functions/nad-fn/testdata/golden/vlanallocation_notReady/vlanallocation-n6.yaml
Labels: lgtm, approved

#194 Return err on `condsdk.New` returns error
  krm-functions/dnn-fn/fn/function.go
  krm-functions/interface-fn/fn/function.go
  krm-functions/ipam-fn/fn/function.go
  krm-functions/nad-fn/mutator/mutator.go
  krm-functions/vlan-fn/fn/function.go
Labels: lgtm, approved, ok-to-test

#178 Pkg Specialization Pipeline tests
  krm-functions/lib/test/krm_fn.go
  krm-functions/pipeline-tests/.gitignore
  krm-functions/pipeline-tests/Makefile
  krm-functions/pipeline-tests/go.mod
  krm-functions/pipeline-tests/go.sum
  krm-functions/pipeline-tests/pipeline_test.go
  krm-functions/pipeline-tests/testdata/real_deployment/_expected.yaml
  krm-functions/pipeline-tests/testdata/real_deployment_2/_expected.yaml
  krm-functions/pipeline-tests/testdata/simplified_deployment/_expected.yaml
  krm-functions/pipeline-tests/testdata/upf_pkg/Kptfile
  krm-functions/pipeline-tests/testdata/upf_pkg/capacity.yaml
  krm-functions/pipeline-tests/testdata/upf_pkg/cluster_context.yaml
  krm-functions/pipeline-tests/testdata/upf_pkg/dnn.yaml
  krm-functions/pipeline-tests/testdata/upf_pkg/interface-n3.yaml
  krm-functions/pipeline-tests/testdata/upf_pkg/interface-n4.yaml
  krm-functions/pipeline-tests/testdata/upf_pkg/interface-n6.yaml
  krm-functions/pipeline-tests/testdata/upf_pkg/package-context.yaml
Labels: area/package-specialization, lgtm, approved

#215 ipam and vlan specializers to controller/pkg/reconcilers
  controllers/pkg/go.mod
  controllers/pkg/go.sum
  controllers/pkg/porch/condition/condition.go
  controllers/pkg/porch/condition/condition_test.go
  controllers/pkg/reconcilers/ipam-specializer/reconciler.go
  controllers/pkg/reconcilers/vlan-specializer/reconciler.go
Labels: lgtm, approved

#213 update Gitea client, readme + token controller
  controllers/pkg/giteaclient/giteaclient.go
  controllers/pkg/go.mod
  controllers/pkg/go.sum
  controllers/pkg/reconcilers/repository/README.md
  controllers/pkg/reconcilers/repository/reconciler.go
  controllers/pkg/reconcilers/token/README.md
  controllers/pkg/reconcilers/token/reconciler.go
Labels: lgtm, approved

#219 Import specializers and update go.mod
  controllers/pkg/reconcilers/token/reconciler.go
  operators/nephio-controller-manager/go.mod
  operators/nephio-controller-manager/go.sum
  operators/nephio-controller-manager/main.go
Labels: lgtm, approved

#220 Pass context from the nephio-controller-manager in SetupWithManager
  controllers/pkg/reconcilers/bootstrap-packages/reconciler.go
  controllers/pkg/reconcilers/bootstrap-secret/reconciler.go
  controllers/pkg/reconcilers/ipam-specializer/reconciler.go
  controllers/pkg/reconcilers/reconciler-interface/reconciler_interface.go
  controllers/pkg/reconcilers/repository/reconciler.go
  controllers/pkg/reconcilers/token/reconciler.go
  controllers/pkg/reconcilers/vlan-specializer/reconciler.go
  operators/nephio-controller-manager/main.go
Labels: lgtm, approved

#227 Gall Start of gitea client in go routine, synchronize the go routine w…
  controllers/pkg/giteaclient/giteaclient.go
  operators/nephio-controller-manager/README.md
  operators/nephio-controller-manager/go.mod
  operators/nephio-controller-manager/go.sum
  operators/nephio-controller-manager/main.go
Labels: lgtm, approved

#232 added bootstrappers
  operators/nephio-controller-manager/go.mod
  operators/nephio-controller-manager/go.sum
  operators/nephio-controller-manager/main.go
Labels: lgtm, approved

#226 Auto-approval controller
  controllers/pkg/porch/client/README.md
  controllers/pkg/porch/client/approval.go
  controllers/pkg/porch/client/client.go
  controllers/pkg/porch/condition/condition.go
  controllers/pkg/reconcilers/approval/README.md
  controllers/pkg/reconcilers/approval/reconciler.go
  controllers/pkg/reconcilers/config/config.go
  operators/nephio-controller-manager/Dockerfile.local
  operators/nephio-controller-manager/Makefile
  operators/nephio-controller-manager/go.mod
  operators/nephio-controller-manager/go.sum
  operators/nephio-controller-manager/main.go
Labels: lgtm, approved

#244 Use regular build, without the replace
  operators/nephio-controller-manager/go.mod
  operators/nephio-controller-manager/go.sum
Labels: lgtm, approved

#228 added controller runtime 15.0
  controllers/pkg/go.mod
  controllers/pkg/go.sum
  controllers/pkg/resource/fake.go
  controllers/specializer-operator/go.mod
  controllers/specializer-operator/go.sum
  krm-functions/dnn-fn/go.mod
  krm-functions/dnn-fn/go.sum
  krm-functions/interface-fn/go.mod
  krm-functions/interface-fn/go.sum
  krm-functions/ipam-fn/go.mod
  krm-functions/ipam-fn/go.sum
  krm-functions/lib/go.mod
  krm-functions/lib/go.sum
  krm-functions/nad-fn/go.mod
  krm-functions/nad-fn/go.sum
  krm-functions/nfdeploy-fn/go.mod
  krm-functions/nfdeploy-fn/go.sum
  krm-functions/pipeline-tests/go.mod
  krm-functions/pipeline-tests/go.sum
  krm-functions/vlan-fn/go.mod
  krm-functions/vlan-fn/go.sum
  operators/nephio-controller-manager/go.mod
  operators/nephio-controller-manager/go.sum
  operators/nephio-controller-manager/main.go
Labels: lgtm, approved
