Repository nephio-project/nephio, pull requests merged in 2023-04, with the labels that each got.

#90 Initial prow job configuration and OWNERS file adjustment
  .prow.yaml
  OWNERS
Labels: do-not-merge/invalid-owners-file, needs-ok-to-test, lgtm, approved

#83 adds support for unit tests, golangci-lint and gosec
  .golangci.yml
  .prow.yaml
  Makefile
Labels: lgtm, approved, ok-to-test

#92 Enable spellcheck
  .gitignore
  .spellcheck.yml
  .wordlist.txt
  README.md
  tox.ini
Labels: lgtm, approved, ok-to-test

#93 Fix the gosec prow configuration
  .prow.yaml
Labels: approved

#64 kpt fn interface library
  go.mod
  go.sum
  krm-functions/lib/interface/v1alpha1/interface.go
  krm-functions/lib/interface/v1alpha1/interface_test.go
Labels: area/package-specialization, lgtm, approved, ok-to-test

#115 Lib design
  krm-functions/lib/design.md
Labels: lgtm, approved

#111 Simplified prow job definitions, changed to use home-brewed gotests image increased lint timeout
  .prow.yaml
  Makefile
Labels: lgtm, approved, ok-to-test

#121 added new generic parser interface
  krm-functions/lib/kubeobject/kubeobject.go
  krm-functions/lib/kubeobject/kubeobject_test.go
  krm-functions/lib/parser/parser.go
Labels: lgtm, approved

#128 Avoid YAML marshaling round-trips and use existing upstream SDK functions
  krm-functions/lib/kubeobject/kubeobject.go
Labels: lgtm, approved

#65 added kpt resourcelist library
  krm-functions/lib/kptrl/kptrl.go
  krm-functions/lib/kptrl/kptrl_test.go
Labels: area/package-specialization, lgtm, approved

#124 Prow job update, license header checking added
  .prow.yaml
Labels: lgtm, approved, ok-to-test

#125 conditional dance sdk
  go.mod
  go.sum
  krm-functions/lib/condkptsdk/design.md
  krm-functions/lib/condkptsdk/inventory.go
  krm-functions/lib/condkptsdk/inventory_diff.go
  krm-functions/lib/condkptsdk/inventory_diff_test.go
  krm-functions/lib/condkptsdk/inventory_ready.go
  krm-functions/lib/condkptsdk/inventory_ready_test.go
  krm-functions/lib/condkptsdk/inventory_resources.go
  krm-functions/lib/condkptsdk/inventory_resources_test.go
  krm-functions/lib/condkptsdk/inventory_test.go
  krm-functions/lib/condkptsdk/sdk.go
  krm-functions/lib/condkptsdk/sdk_list_inventory.go
  krm-functions/lib/condkptsdk/sdk_populate_inventory.go
  krm-functions/lib/condkptsdk/sdk_stage1.go
  krm-functions/lib/condkptsdk/sdk_stage2.go
  krm-functions/lib/condkptsdk/sdk_test.go
  krm-functions/lib/condkptsdk/sdk_updates.go
  krm-functions/lib/condkptsdk/sdk_watches.go
  krm-functions/lib/condkptsdk/utils.go
  krm-functions/lib/condkptsdk/utils_test.go
  krm-functions/lib/kubeobject/kubeobject.go
  krm-functions/lib/kubeobject/kubeobject_test.go
Labels: lgtm, approved

#135 sdk nil pointer. check missing
  krm-functions/lib/condkptsdk/inventory_ready.go
Labels: lgtm, approved

#134 Add helper functions for testing KRM functions
  krm-functions/lib/test/helpers.go
  krm-functions/lib/test/krm_fn.go
  krm-functions/lib/test/kubeobject.go
Labels: lgtm, approved

#133 Add KubeObject setters that keep formatting to "kubeobject" lib
  .gitignore
  go.mod
  krm-functions/lib/kubeobject/kubeobject.go
  krm-functions/lib/kubeobject/kubeobject_test.go
  krm-functions/lib/kubeobject/testdata/.gitignore
  krm-functions/lib/kubeobject/testdata/comments.yaml
  krm-functions/lib/kubeobject/testdata/comments_expected.yaml
  krm-functions/lib/kubeobject/testdata/empty_status.yaml
  krm-functions/lib/kubeobject/testdata/empty_status_expected.yaml
  krm-functions/lib/kubeobject/testdata/status_comments.yaml
  krm-functions/lib/kubeobject/testdata/status_comments_expected.yaml
Labels: lgtm, approved

#140 VLAN alloc with new KO
  go.mod
  go.sum
  krm-functions/lib/condkptsdk/inventory_diff_test.go
  krm-functions/lib/kptrl/kptrl_test.go
  krm-functions/lib/vlanalloc/v1alpha1/vlanalloc.go
  krm-functions/lib/vlanalloc/v1alpha1/vlanalloc_test.go
Labels: lgtm, approved
