Repository nephio-project/nephio, pull requests merged in 2024-03, with the labels that each got.

#561 Add liamfallon to OWNERS file
  OWNERS
Labels: lgtm, approved

#559 (docs): added contributing.md file
  CONTRIBUTING.md
Labels: lgtm, approved, ok-to-test

#485 Add efiacor to OWNERS file
  OWNERS
Labels: lgtm, approved

#560 (docs): ossf best practices badge
  README.md
Labels: needs-ok-to-test, lgtm, approved

#482 Add mockery test for approval reconciler
  controllers/pkg/.mockery.yaml
  controllers/pkg/reconcilers/approval/reconciler.go
  controllers/pkg/reconcilers/approval/reconciler_test.go
Labels: lgtm, approved

#558 (feat): added dependabot
  .github/dependabot.yml
Labels: lgtm, approved, ok-to-test
