Repository nephio-project/nephio, pull requests merged in 2025-03, with the labels that each got.

#869 add missing license headers
  controllers/pkg/giteaclient/giteaclient_test.go
  controllers/pkg/giteaclient/mock_GiteaClient.go
  controllers/pkg/mocks/external/client/mock_Client.go
  controllers/pkg/mocks/external/reader/mock_Reader.go
  controllers/pkg/reconcilers/spire-bootstrap/reconciler_test.go
  krm-functions/configinject-fn/Makefile
  krm-functions/dnn-fn/Makefile
  krm-functions/gen-configmap-fn/Makefile
  krm-functions/gen-configmap-fn/main.go
  krm-functions/gen-kustomize-res/Makefile
  krm-functions/interface-fn/Makefile
  krm-functions/ipam-fn/Makefile
  krm-functions/lib/Makefile
  krm-functions/nad-fn/Makefile
  krm-functions/nad-fn/main.go
  krm-functions/nfdeploy-fn/Makefile
  krm-functions/nfdeploy-fn/main.go
  krm-functions/pipeline-tests/Makefile
  krm-functions/ueransim-deploy-fn/Makefile
  krm-functions/vlan-fn/Makefile
  operators/focom-operator/Makefile
  operators/nephio-controller-manager/Makefile
  operators/o2ims-operator/tests/create-cluster.sh
  testing/mockeryutils/Makefile
Labels: lgtm, approved, ok-to-test

#872 Update nephio related dependencies
  controllers/pkg/go.mod
  controllers/pkg/go.sum
  controllers/pkg/porch/condition/condition.go
  controllers/pkg/porch/condition/condition_test.go
  controllers/pkg/porch/util/packagevariant_test.go
  controllers/pkg/reconcilers/approval/reconciler.go
  krm-functions/configinject-fn/go.mod
  krm-functions/configinject-fn/go.sum
  krm-functions/dnn-fn/go.mod
  krm-functions/dnn-fn/go.sum
  krm-functions/interface-fn/go.mod
  krm-functions/interface-fn/go.sum
  krm-functions/ipam-fn/go.mod
  krm-functions/ipam-fn/go.sum
  krm-functions/lib/go.mod
  krm-functions/lib/go.sum
  krm-functions/nad-fn/go.mod
  krm-functions/nad-fn/go.sum
  krm-functions/nfdeploy-fn/go.mod
  krm-functions/nfdeploy-fn/go.sum
  krm-functions/pipeline-tests/go.mod
  krm-functions/pipeline-tests/go.sum
  krm-functions/ueransim-deploy-fn/go.mod
  krm-functions/ueransim-deploy-fn/go.sum
  krm-functions/vlan-fn/go.mod
  krm-functions/vlan-fn/go.sum
  operators/nephio-controller-manager/go.mod
  operators/nephio-controller-manager/go.sum
Labels: sig/automation, lgtm, approved, dependencies, area/platform

#883 Add bug_report issue template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: enhancement, sig/release, lgtm, approved

#886 Change Nephio controllers to use numeric package revisions on Porch packages
  controllers/pkg/go.mod
  controllers/pkg/go.sum
  krm-functions/configinject-fn/fn/function.go
  krm-functions/configinject-fn/go.mod
  krm-functions/configinject-fn/go.sum
  krm-functions/dnn-fn/go.mod
  krm-functions/dnn-fn/go.sum
  krm-functions/gen-configmap-fn/go.mod
  krm-functions/gen-configmap-fn/go.sum
  krm-functions/gen-kustomize-res/go.mod
  krm-functions/gen-kustomize-res/go.sum
  krm-functions/interface-fn/go.mod
  krm-functions/interface-fn/go.sum
  krm-functions/ipam-fn/go.mod
  krm-functions/ipam-fn/go.sum
  krm-functions/lib/go.mod
  krm-functions/lib/go.sum
  krm-functions/nad-fn/go.mod
  krm-functions/nad-fn/go.sum
  krm-functions/nfdeploy-fn/go.mod
  krm-functions/nfdeploy-fn/go.sum
  krm-functions/pipeline-tests/go.mod
  krm-functions/pipeline-tests/go.sum
  krm-functions/ueransim-deploy-fn/go.mod
  krm-functions/ueransim-deploy-fn/go.sum
  krm-functions/vlan-fn/go.mod
  krm-functions/vlan-fn/go.sum
  operators/focom-operator/go.mod
  operators/focom-operator/go.sum
  operators/nephio-controller-manager/go.mod
  operators/nephio-controller-manager/go.sum
  testing/mockeryutils/go.mod
  testing/mockeryutils/go.sum
Labels: lgtm, approved
