Repository nephio-project/nephio, pull requests merged in 2025-02, with the labels that each got.

#844 O2-IMS Operator
  operators/o2ims-operator/Dockerfile
  operators/o2ims-operator/README.md
  operators/o2ims-operator/controllers/__init__.py
  operators/o2ims-operator/controllers/manager.py
  operators/o2ims-operator/controllers/provisioning_request_controller.py
  operators/o2ims-operator/controllers/provisioning_request_validation_controller.py
  operators/o2ims-operator/controllers/utils.py
  operators/o2ims-operator/requirements.txt
  operators/o2ims-operator/tests/__init__.py
  operators/o2ims-operator/tests/create-cluster.sh
  operators/o2ims-operator/tests/deployment/operator.yaml
  operators/o2ims-operator/tests/mgmt-cluster.yaml
  operators/o2ims-operator/tests/sa-test-pod.yaml
  operators/o2ims-operator/tests/test_utils.py
  operators/o2ims-operator/tests/unit_test_requirements.txt
  operators/o2ims-operator/tox.ini
Labels: lgtm, approved

#845 O2 IMS Operator dev image build
  .prow.yaml
Labels: lgtm, approved

#850 Add prow docker build job for focom operator image
  .prow.yaml
Labels: sig/release, lgtm, approved, area/oran

#856 Fix focom docker build job
  .prow.yaml
Labels: lgtm, approved

#809 Workload Identity reconciler integration using SPIFFE
  controllers/pkg/go.mod
  controllers/pkg/go.sum
  controllers/pkg/reconcilers/spire-bootstrap/kubeconfigTypes.go
  controllers/pkg/reconcilers/spire-bootstrap/reconciler.go
  controllers/pkg/reconcilers/spire-bootstrap/reconciler_test.go
  controllers/pkg/reconcilers/spire-bootstrap/spiffeutils.go
  operators/nephio-controller-manager/go.mod
  operators/nephio-controller-manager/main.go
Labels: enhancement, sig/automation, lgtm, approved, ok-to-test, area/security

#861 updates the dockerfile to run kopf as nonroot
  operators/o2ims-operator/Dockerfile
  operators/o2ims-operator/README.md
Labels: lgtm, approved

#863 Fix openssf github action workflow
  .github/workflows/openssf_scorecard.yaml
Labels: lgtm

#860 Bump go version to 1.23.5
  controllers/pkg/go.mod
  krm-functions/configinject-fn/Dockerfile
  krm-functions/configinject-fn/go.mod
  krm-functions/dnn-fn/Dockerfile
  krm-functions/dnn-fn/go.mod
  krm-functions/gen-configmap-fn/Dockerfile
  krm-functions/gen-kustomize-res/Dockerfile
  krm-functions/interface-fn/Dockerfile
  krm-functions/interface-fn/go.mod
  krm-functions/ipam-fn/Dockerfile
  krm-functions/ipam-fn/go.mod
  krm-functions/lib/go.mod
  krm-functions/nad-fn/Dockerfile
  krm-functions/nad-fn/go.mod
  krm-functions/nfdeploy-fn/Dockerfile
  krm-functions/nfdeploy-fn/go.mod
  krm-functions/pipeline-tests/go.mod
  krm-functions/ueransim-deploy-fn/Dockerfile
  krm-functions/ueransim-deploy-fn/go.mod
  krm-functions/vlan-fn/Dockerfile
  krm-functions/vlan-fn/go.mod
  operators/focom-operator/go.mod
  operators/nephio-controller-manager/Dockerfile
  operators/nephio-controller-manager/go.mod
  testing/mockeryutils/go.mod
Labels: sig/automation, lgtm, approved, ok-to-test, area/platform

#864 Address ossf vuln
  krm-functions/configinject-fn/Dockerfile
  krm-functions/dnn-fn/Dockerfile
  krm-functions/gen-configmap-fn/Dockerfile
  krm-functions/gen-configmap-fn/go.mod
  krm-functions/gen-kustomize-res/Dockerfile
  krm-functions/gen-kustomize-res/go.mod
  krm-functions/interface-fn/Dockerfile
  krm-functions/ipam-fn/Dockerfile
  krm-functions/nad-fn/Dockerfile
  krm-functions/nfdeploy-fn/Dockerfile
  krm-functions/ueransim-deploy-fn/Dockerfile
  krm-functions/vlan-fn/Dockerfile
  operators/focom-operator/Dockerfile
  operators/focom-operator/config/manager/kustomization.yaml
  operators/focom-operator/go.mod
  operators/focom-operator/go.sum
  operators/nephio-controller-manager/Dockerfile
  operators/nephio-controller-manager/Dockerfile.local
  operators/o2ims-operator/Dockerfile
  operators/o2ims-operator/requirements.txt
Labels: approved, area/security
